### ISSUE TITLE
Alarms has not been created

### ISSUE THREAD

**Issue by sanjap** [Star2Billing/a2billing#54]
One of the table names for alarms is 'maxvalue' which in the latest release of MySQL is a reserved SQL word. Getting SQL syntax error with this name in the SQL command.

**Comment by Ubunter** [comment]
Hello,
We have solved this bug...
It's because the alarms table, cc_alarm, has a column called maxvalue and it turns out that maxvalue is a keyword in mysql.

**SOLUTION:**
In ./admin/Public/form_data/FG_var_alarm.inc added backticks around maxvalue in the setup of  `$HD_Form -> FieldViewElement and  $HD_Form -> FieldEditElement`

Hope that we're right and correct, as it's working fine now, for us, and it's up to areski and the developers to prove this solution and close this bug.

Regards,

**Comment by areski** [comment]
patch here: https://github.com/Star2Billing/a2billing/commit/c879be4dd0aa02710800a93e68e6ebf64f85b606

**Comment by mason-chase** [comment]
In my opinion: The all fields in entire statement should be enclosed with backticks. this will also improve MySQL parsing of any SQL statement.
